name: Update Tables

on:
  schedule:
    # täglich um 03:00 Uhr
    - cron: "0 3 * * *"

    # samstags & sonntags alle 30 Minuten zwischen 10 und 20 Uhr
    - cron: "*/30 10-20 * * SAT,SUN"

  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    env:
      NUM_FUTURE_GAMES: ${{ vars.NUM_FUTURE_GAMES }}

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Python installieren
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Abhängigkeiten installieren
        run: pip install beautifulsoup4 requests

      - name: Tabellen aktualisieren
        run: python scraper.py

      - name: Änderungen committen
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update tables" || echo "Keine Änderungen"
          git push
